### ISSUE TITLE
waitting solution of ModuleNotFoundError: No module named 'aliyunsdkcore'

### ISSUE THREAD

**Issue by whmc76** [THtianhao/ComfyUI-Portrait-Maker#2]

**Comment by Kinglord** [comment]
This is a deprecated package and I don't know why modelscope still uses it, but as far as I can tell it doesn't work on newer versions of python that come bundled with comfyui, not sure how the author of this got it running :D

I'm going to make another issue here so that the author knows that at least people running standalone comfy can't use this.

**Comment by THtianhao** [comment]
Lol ,u are right

**Comment by JacksonTian** [comment]
I build a new workflow to reproduce it: https://github.com/JacksonTian/ComfyUI-Portrait-Maker/actions/runs/6582572986/job/17884273824 . But installation is OK.

**Comment by THtianhao** [comment]
> I build a new workflow to reproduce it: https://github.com/JacksonTian/ComfyUI-Portrait-Maker/actions/runs/6582572986/job/17884273824 . But installation is OK.
Thank u for u contribute, But this bug only appears when using the windows zip package of ComfyUI, There has an independent python environment. This problem will only occur when using that python environment.

**Comment by THtianhao** [comment]
> I build a new workflow to reproduce it: https://github.com/JacksonTian/ComfyUI-Portrait-Maker/actions/runs/6582572986/job/17884273824 . But installation is OK.

Thank u for u contribute ,This bug only appears when using the Windows System zip package of ComfyUI, There has an independent python environment. This problem will only occur when using that python environment.

**Comment by THtianhao** [comment]
pip install aliyun-python-sdk-core-v3==2.13.10
